#!/bin/bash

#  This file is part of fastboot, an AVR serial bootloader.
#  Copyright (C) 2010 Heike C. Zimmerer <hcz@hczim.de>
# 
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# convert lines of the form
#
# 23c23
# < e066
# ---
# > e06c
#
# (as generated by a 2-byte hexdump of the flash image) into hes from:
#
# (0x17) 0x2c 
# < e066
# > e06c
#

while read line; do
    [[ "$line" =~ '---' ]] && continue
    if [[ "$line" =~ ([0-9]+)c([0-9]+) ]]; then
        old=$((${BASH_REMATCH[2]} - 1))
        new=$((${BASH_REMATCH[1]} - 1))
        printf "\n%s\n" "$line"
        if [ "$old" = "$new" ]; then
            printf "(%#04x) %#04x:\n" \
                "$old" "$((old * 2))"
        else
            printf "(%#04x) %#04x...(%#04x) %#04x:\n" \
                "$old" "$((old * 2))" \
                "$new" "$((new * 2))" 
        fi
    else
        printf "%s\n" "$line"
    fi
done
